name: clothes_on_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: ^6.2.1
  path: ^1.9.0
  sqflite: ^2.3.2
  


flutter:
  uses-material-design: true
  assets:
    - "assets/splash_clothes.png"
    - "assets/splash_clothes-removebg-preview.png"
    - "assets/login_screen.png"
