name: custom_paint_cricket_field
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cricket_run_map: ^1.0.1
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  wagon_wheel: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\batsman.svg
